### ISSUE TITLE
proxy-error after create new instance

### ISSUE THREAD

**Issue by hsquividant** [Mario-35/Stean#1]
when I create a new instance on the sensorthings.geosas.fr server, I get a new error “Proxy Error”.
![proxy-error](https://github.com/user-attachments/assets/35040d3d-bb57-4bee-a49b-4fc83e3e3f7e)

**Comment by Mario-35** [comment]
Yes the fact that when a new service is added by the /Service route the default new user is the service name cause some trouble. 

it's fixed now

https://github.com/Mario-35/Stean/commit/c3a0b7e07713a5a5fbe30f6900dc92a14548b7ea
