### ISSUE TITLE
Maybe @iot.count ould return an integer rather than a string

### ISSUE THREAD

**Issue by hsquividant** [Mario-35/STEAN#1]
Actually "count" request return a string, maybe it would be better to return an integer as FROST Server do.
STEAN : https://sensorthings.geosas.fr/bosco/v1.0/Things?$count=true
FROST : https://frost.geosas.fr/bosco/v1.0/Things?$count=true

**Comment by hsquividant** [comment]
The example of $count query option you can find in "OGC SensorThings API Part 1: Sensing" document returns an integer value : https://docs.ogc.org/is/15-078r6/15-078r6.html#53

**Comment by Mario-35** [comment]
I put an integer as FROST Server to be compatible BUT FROST is wrong  bigSerial that are use to get great number as id have te be use as a string ... but i admit that is ambigous.

**Comment by Mario-35** [comment]
For count it's ok it was a mistake,  AND count = true is ok BUT to be improved on huge database.

**Comment by hsquividant** [comment]
> For count it's ok it was a mistake, AND count = true is ok BUT to be improved on huge database.

Are you sure ? cf https://api.geosas.fr/agrhys/v1.0/Observations?$count=true

**Comment by hsquividant** [comment]
It's OK now. Thanks !
