### ISSUE TITLE
Error in filter request

### ISSUE THREAD

**Issue by t-loree** [Mario-35/STEAN#2]
Error in filter request :

| Filter geometry, same geometry in Frost and Stean                                                                                                                                                                	| Success 	|
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|---------	|
| https://frost.geosas.fr/bosco/v1.0/Locations?$filter=geo.intersects(location, geography'POLYGON ((-2.095 47.975, -2.095 47.999, -2.065 47.999, -2.065 47.975, -2.095 47.975))') 	| Ok      	|
| https://api.geosas.fr/bosco/v1.0/Locations?$filter=geo.intersects(location, geography'POLYGON ((-2.095 47.975, -2.095 47.999, -2.065 47.999, -2.065 47.975, -2.095 47.975))')   	| Error   	|
| https://frost.geosas.fr/bosco/v1.0/Locations?$filter=st_intersects(location, geography'POLYGON ((-2.095 47.975, -2.095 47.999, -2.065 47.999, -2.065 47.975, -2.095 47.975))')  	| Ok      	|
| https://api.geosas.fr/bosco/v1.0/Locations?$filter=st_intersects(location, geography'POLYGON ((-2.095 47.975, -2.095 47.999, -2.065 47.999, -2.065 47.975, -2.095 47.975))')    	| Error   	|

| Filter Time                                                                                                                                                                               	| Success 	|
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|---------	|
| https://frost.geosas.fr/bosco/v1.0/Datastreams?$filter=phenomenonTime%20eq%202017-01-03T12:00:00Z/2022-11-11T12:00:00Z                                                                    	| Ok      	|
| https://api.geosas.fr/hubeau/v1.0/Datastreams?$filter=phenomenonTime%20eq%202017-01-03T12:00:00Z/2022-11-11T12:00:00Z                                                                     	| Error   	|
| https://frost.geosas.fr/bosco/v1.0/Things?$filter=Datastreams/Observations/resultTime%20ge%202021-06-01T00:00:00Z%20and%20Datastreams/Observations/resultTime%20le%202022-07-01T00:00:00Z 	| Ok      	|
| https://api.geosas.fr/hubeau/v1.0/Things?$filter=Datastreams/Observations/resultTime%20ge%202020-06-01T00:00:00Z%20and%20Datastreams/Observations/resultTime%20le%202022-07-01T00:00:00Z  	| Error   	|
| https://frost.geosas.fr/bosco/v1.0/Datastreams?$expand=Observations&$filter=phenomenonTime%20gt%202021-11-11T12:00:00Z | Ok |
| https://api.geosas.fr/hubeau/v1.0/Datastreams?$expand=Observations&$filter=phenomenonTime%20gt%202021-11-11T12:00:00Z | Error |
| https://frost.geosas.fr/bosco/v1.0/Datastreams?$expand=Observations&$filter=Observations/phenomenonTime%20eq%202017-01-04T12:00:00Z | Ok |
| https://api.geosas.fr/hubeau/v1.0/Datastreams?$expand=Observations&$filter=Observations/phenomenonTime%20eq%201967-01-01T00:00:00+01:00 | Error |
 

| Other Filter                                                                                                                                                                               	| Success 	|
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|---------	|
| https://frost.geosas.fr/bosco/v1.0/Datastreams?$filter=Observations/result%20gt%2050                                              	| Ok      	|
| https://api.geosas.fr/hubeau/v1.0/Datastreams?$filter=Observations/result%20gt%2050           	| Error   	|
| https://frost.geosas.fr/bosco/v1.0/Things?$filter=Datastreams/unitOfMeasurement/name%20eq%20%27Percentage%27| Ok      	|
| https://api.geosas.fr/hubeau/v1.0/Things?$filter=Datastreams/unitOfMeasurement/name%20eq%20%27Litre%20par%20seconde%27  	| Error   	|
|https://api.geosas.fr/rennesmetro/v1.0/Things?$filter=Datastreams/ObservedProperty/description eq 'Capteur de pression'  ---> Cette requête renvoie un datastream mais ObservedProperty/description eq 'Capteur de pression' n'exite pas c'est le nom du datastream  | Error |

**Comment by Mario-35** [comment]
corrige : https://api.geosas.fr/hubeau/v1.0/Datastreams?$filter=phenomenonTime%20eq%202017-01-03T12:00:00Z/2022-11-11T12:00:00Z

MAIS il s'agissait 'd'un trou dans la raquette' car la recherche est touchy car il s'agit d'une chaine de caractères pas d'une période ....

**Comment by Mario-35** [comment]
Error in filter request :

| Filter geometry, same geometry in Frost and Stean                                                                                                                                                                	| Success 	|
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|---------	|
| https://frost.geosas.fr/bosco/v1.0/Locations?$filter=geo.intersects(location, geography'POLYGON ((-2.095 47.975, -2.095 47.999, -2.065 47.999, -2.065 47.975, -2.095 47.975))') 	| Ok      	|
| https://api.geosas.fr/bosco/v1.0/Locations?$filter=geo.intersects(location, geography'POLYGON ((-2.095 47.975, -2.095 47.999, -2.065 47.999, -2.065 47.975, -2.095 47.975))')   	| Error   	|
| https://frost.geosas.fr/bosco/v1.0/Locations?$filter=st_intersects(location, geography'POLYGON ((-2.095 47.975, -2.095 47.999, -2.065 47.999, -2.065 47.975, -2.095 47.975))')  	| Ok      	|
| https://api.geosas.fr/bosco/v1.0/Locations?$filter=st_intersects(location, geography'POLYGON ((-2.095 47.975, -2.095 47.999, -2.065 47.999, -2.065 47.975, -2.095 47.975))')    	| Error   	|


| Filter Time                                                                                                                                                                               	| Success 	|
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|---------	|
| https://frost.geosas.fr/bosco/v1.0/Datastreams?$filter=phenomenonTime%20eq%202017-01-03T12:00:00Z/2022-11-11T12:00:00Z                                                                    	| Ok      	|
| https://api.geosas.fr/hubeau/v1.0/Datastreams?$filter=phenomenonTime%20eq%202017-01-03T12:00:00Z/2022-11-11T12:00:00Z                                                                     	| Error   	|
| https://frost.geosas.fr/bosco/v1.0/Things?$filter=Datastreams/Observations/resultTime%20ge%202021-06-01T00:00:00Z%20and%20Datastreams/Observations/resultTime%20le%202022-07-01T00:00:00Z 	| Ok      	|
| https://api.geosas.fr/hubeau/v1.0/Things?$filter=Datastreams/Observations/resultTime%20ge%202020-06-01T00:00:00Z%20and%20Datastreams/Observations/resultTime%20le%202022-07-01T00:00:00Z  	| Error   	|
| https://frost.geosas.fr/bosco/v1.0/Datastreams?$expand=Observations&$filter=phenomenonTime%20gt%202021-11-11T12:00:00Z | Ok |
| https://api.geosas.fr/hubeau/v1.0/Datastreams?$expand=Observations&$filter=phenomenonTime%20gt%202021-11-11T12:00:00Z | Error |
| https://frost.geosas.fr/bosco/v1.0/Datastreams?$expand=Observations&$filter=Observations/phenomenonTime%20eq%202017-01-04T12:00:00Z | Ok |
| https://api.geosas.fr/hubeau/v1.0/Datastreams?$expand=Observations&$filter=Observations/phenomenonTime%20eq%201967-01-01T00:00:00+01:00 | Error |
 

| Other Filter                                                                                                                                                                               	| Success 	|
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|---------	|
| https://frost.geosas.fr/bosco/v1.0/Datastreams?$filter=Observations/result%20gt%2050                                              	| Ok      	|
| https://api.geosas.fr/hubeau/v1.0/Datastreams?$filter=Observations/result%20gt%2050           	| Error   	|
| https://frost.geosas.fr/bosco/v1.0/Things?$filter=Datastreams/unitOfMeasurement/name%20eq%20%27Percentage%27| Ok      	|
| https://api.geosas.fr/hubeau/v1.0/Things?$filter=Datastreams/unitOfMeasurement/name%20eq%20%27Litre%20par%20seconde%27  	| Error   	|
|https://api.geosas.fr/rennesmetro/v1.0/Things?$filter=Datastreams/ObservedProperty/description eq 'Capteur de pression'  ---> Cette requête renvoie un datastream mais ObservedProperty/description eq 'Capteur de pression' n'exite pas c'est le nom du datastream  | Error |

**Comment by Mario-35** [comment]
all are correct now
