### ISSUE TITLE
login returns 401 error for new instance just created

### ISSUE THREAD

**Issue by hsquividant** [Mario-35/Stean#2]
After creating a new instance, @t-loree  can't connect with the login/passwd he just created. 
The api returns a 401 error: '{“code”:401, “message”: “Unauthorized”}'.
When I look at the postgres console, the database owner is postgres and not the postgres user I've just created, but maybe that's normal?
pm2 logs only returns :
[[39m 28/10/2024 10:34:53 <-- POST /tom_2810/v1.1/login
[[39m 28/10/2024 10:34:53 xxx POST /tom_2810/v1.1/login 401 1ms -
Any idea ?

**Comment by Mario-35** [comment]
the bug has already been fixed it is no longer possible to create a postgres user which has depending on its rights the possibility of changing the original postgres password. The solution is to create a service by logging in with the new password "accidentally" saved. In the creation of the service put the password leaving the postgres user. Finally make an update to prevent this from happening again.
![image](https://github.com/user-attachments/assets/b38f58bc-e76d-4480-a39a-8aa4ae6e511f)

**Comment by t-loree** [comment]
For more information this is what i did:

![Capture d’écran du 2024-10-29 09-34-25](https://github.com/user-attachments/assets/f5aac002-3420-4615-81e0-e3cb6b4dd8c3)


![Capture d’écran du 2024-10-29 09-35-58](https://github.com/user-attachments/assets/e1641f3e-ae5c-4366-9b71-697c34712426)

When i try to logging with : 
```
data={
    "username": "test2910",
    "password": "My new password"
}

```
i have : {"code":401,"message":"Unauthorized"}

By the way, if you put two different  password for "New user password" and "repeat password", there is no warning and the new service is created.

**Comment by Mario-35** [comment]
I am not be able to reproduce it, but I rewrite the service code and I test in few different use case,  let me know if it's better ...

You have to update 0.9.4

**Comment by hsquividant** [comment]
I've just updated to 0.9.4, @t-loree, can you test again ?

**Comment by t-loree** [comment]
It'works !
Except the new user password and the repeat password (it can lead to mistakes (that was my case)) : 
![image](https://github.com/user-attachments/assets/d9f9fbba-8dc8-4e42-8134-78f6ab3313cc)
