### ISSUE TITLE
HistoricalLocation issue in test ?

### ISSUE THREAD

**Issue by charlycou** [Mario-35/Stean#3]
In your test Locations(2) has several HistoricalLocation entities associated.  http://sensorthings.geosas.fr/test/v1.1/Locations(2)/HistoricalLocations returns:
- http://sensorthings.geosas.fr/test/v1.1/HistoricalLocations(2)
- http://sensorthings.geosas.fr/test/v1.1/HistoricalLocations(6)

However navigating from HistoricalLocation(6) to associated locations does not return Locations(2) but only Location(6).  http://sensorthings.geosas.fr/test/v1.1/HistoricalLocations(6)/Locations.

**Comment by Mario-35** [comment]
thanks charly I'll see that I think it's due to error with singular relation

**Comment by Mario-35** [comment]
I think it's resolve
