### ISSUE TITLE
Get a new token Token documentation 

### ISSUE THREAD

**Issue by t-loree** [Mario-35/Stean#5]
In all the documentation, there are examples in the form of http, curl, javascript, python except for the  Get a new Token part (just http and curl).
https://sensorthings.umrsas.inrae.fr/#api-Token

**Comment by Mario-35** [comment]
This is normal you can't get a token without send infos it's a non sense.

token work only on post

**Comment by t-loree** [comment]
Yes token work only on post, when i said "Get a new Token" i'm talking about the chapter "Get a new Token"
![image](https://github.com/user-attachments/assets/a43adaa5-d5f6-4c6d-811d-a59ac7db07c6)
It's a detail but the exemples for javascript and python are missing
