### ISSUE TITLE
Filter result error 400

### ISSUE THREAD

**Issue by t-loree** [Mario-35/Stean#8]
https://sensorthings.geosas.fr/rennesmetro/v1.1/Datastreams(1)/Observations?$filter=result%20lt%202

return 

``` json
{
  "code": 400,
  "message": "Bad Request",
  "detail": "syntaxe en entrée invalide pour le type numeric : «  \"Humidite volumique du sol relative\": 43.4 »"
}
```

**Comment by Mario-35** [comment]
It's a bug I patch, it works now on next update.

the bug was that stean not detect datastream entity in that request
